name: clicktap
channels:
  - conda-forge
  - defaults
dependencies:
  - adwaita-icon-theme=49.0=unix_0
  - aom=3.9.1=h7bae524_0
  - atk-1.0=2.38.0=hd03087b_2
  - baumwelch=0.3.11=ha7d2532_0
  - biopython=1.86=py311h9408147_0
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py311h69b7e7c_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h5a5e7c7_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dataclassy=1.0.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - epoxy=1.5.10=hc919400_2
  - ffmpeg=7.1.0=gpl_h92f8dbd_105
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - glib-tools=2.84.0=h1dc7a0c_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - graphviz=12.2.1=hff64154_1
  - greenlet=3.2.4=py311hf719da1_1
  - gtk3=3.24.43=h7492e44_1
  - gts=0.7.6=he42f4ea_4
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.1.0=hab40de2_0
  - hdbscan=0.8.39=py311h09efe57_1
  - hicolor-icon-theme=0.17=hce30654_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - kaldi=5.5.1172=cpu_h0f61937_1
  - kalpy=0.8.2=py311h5a5e7c7_0
  - kiwisolver=1.4.9=py311h26d6576_2
  - kneed=0.8.5=pyhd8ed1ab_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libass=0.17.3=h68e5b86_2
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=21.1.5=hf598326_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libflac=1.4.3=hb765f3a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgd=2.3.3=hb2c3a21_11
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.84.0=hdff4504_0
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblapacke=3.9.0=38_h1b118fd_openblas
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopenvino=2024.4.0=hbfeda7a_2
  - libopenvino-arm-cpu-plugin=2024.4.0=hbfeda7a_2
  - libopenvino-auto-batch-plugin=2024.4.0=hf276634_2
  - libopenvino-auto-plugin=2024.4.0=hf276634_2
  - libopenvino-hetero-plugin=2024.4.0=h03892cd_2
  - libopenvino-ir-frontend=2024.4.0=h03892cd_2
  - libopenvino-onnx-frontend=2024.4.0=h7f5a098_2
  - libopenvino-paddle-frontend=2024.4.0=h7f5a098_2
  - libopenvino-pytorch-frontend=2024.4.0=h5833ebf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h9d544f2_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5833ebf_2
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libpq=17.3=h6896619_0
  - libprotobuf=5.28.2=h8f0b736_0
  - librosa=0.11.0=pyhd8ed1ab_0
  - librsvg=2.58.4=h266df6f_2
  - libsndfile=1.2.2=h9739721_1
  - libsqlite=3.51.0=h8adb53f_0
  - libtiff=4.7.0=hfce79cd_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.5=hbbdcc80_0
  - libxslt=1.1.39=h223e5b9_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - mad=0.15.1b=hbdafb3b_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.10.7=py311h29553df_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - montreal-forced-aligner=3.3.8=pyhd8ed1ab_0
  - mpg123=1.32.9=hf642e45_0
  - msgpack-python=1.1.2=py311h5a5e7c7_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - ngram=1.3.17=ha7d2532_0
  - numba=0.62.1=py311h922685c_0
  - numpy=2.3.4=py311h8685306_0
  - openfst=1.8.4=ha393de7_1
  - openh264=2.5.0=h774163f_0
  - openjpeg=2.5.3=h889cd5d_1
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.3=h5fd7515_1
  - pcre2=10.44=ha881caa_2
  - pgvector=0.8.0=hed0719a_1
  - pgvector-python=0.4.1=pyhc48fcf7_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - postgresql=17.3=hb80eeff_0
  - praatio=6.2.0=pyhd8ed1ab_1
  - psycopg2=2.9.9=py311h057640d_2
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.14=h13dd4ca_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynini=2.1.7=py311h5a5e7c7_2
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.11.9=h932a869_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyyaml=6.0.3=py311ha9b3269_0
  - qhull=2020.2=h420ef59_5
  - readline=8.3=h0b18652_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-click=1.9.4=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py311h0f965f6_0
  - scipy=1.16.3=py311h2734c94_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sox=14.4.2=h3df6788_1019
  - soxr=0.1.3=h5008568_3
  - soxr-python=1.0.0=py311h251fd82_1
  - sqlalchemy=2.0.44=py311h9408147_0
  - sqlite=3.51.0=hab6afd1_0
  - standard-aifc=3.13.0=py311h267d04e_3
  - standard-sunau=3.13.0=py311h267d04e_3
  - svt-av1=2.3.0=hf24288c_0
  - tbb=2022.1.0=h9541205_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzcode=2025b=h5505292_0
  - unicodedata2=17.0.0=py311h9408147_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.25.0=py311h5bb9006_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - audioread==3.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - llvmlite==0.45.1
      - pandas==2.3.3
      - pillow==12.0.0
      - pycparser==2.23
      - pyside6==6.10.0
      - pyside6-addons==6.10.0
      - pyside6-essentials==6.10.0
      - pytz==2025.2
      - seaborn==0.13.2
      - shiboken6==6.10.0
      - textgrid==1.6.1
      - tzdata==2025.2
prefix: /opt/homebrew/anaconda3/envs/clicktap
